### ISSUE TITLE
No write access on repository

### ISSUE THREAD

**Issue by LndH** [osoc22/technical-support#1]
**Is your request related to a problem? Please describe.**
My team does not have write access (only read access) to the https://github.com/osoc22/project-vanhout-experiments repository.

**Describe the solution you'd like**
We would like to get write access to the repository.

**Describe alternatives you've considered**
N\A

**Additional context**
![Screenshot 2022-07-05 at 09 31 44](https://user-images.githubusercontent.com/17167523/177274206-54059e2d-d477-47d9-b65c-9561f36b0b9f.png)

**Comment by LotuxPunk** [comment]
Oops! It's fixed. :)
