### ISSUE TITLE
inspector-widget : Access to a VPS for deployment

### ISSUE THREAD

**Issue by arthurco** [osoc22/technical-support#10]
**Is your request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Hello, we'd like to have a VPS available to be able to properly deploy our project. (or something else if you can offer us a solution that'll do the work)
Since we absolutely need at least 2 Docker containers that can have access to each-other (and one of the container should only be accessible from the other), we think that it is necessary for us to have that.
As we're basically running an instance of google chrome inside a container and connecting to its remote-debugging port (and the chrome remote debug thing has no such thing as authentication) we feel like having a VPS is the only 'good' way to go.

**Describe alternatives you've considered**
We've looked into using Digital Ocean App thing but unfortunately it does not support docker-compose files and we've already deployed our front-end.

**Comment by jbelien** [comment]
Hello @arthurco ,

Looking at https://github.com/osoc22/project-inspector-widget, I'm not exactly sure why a VPS/Droplet is needed but considering it's end of week 3, I won't argue.

Who will manage the VPS/Droplet ?
Could you ask this person to send me his/her **public** SSH key (in private message on Discord) ?

---

@LotuxPunk Could you also send me your **public** SSH key (in private message on Discord) so I can also give you access to the Droplet ?

**Comment by jbelien** [comment]
Droplet is live: `161.35.150.132`

@arthurco You have `root` access with your SSH key.
