### ISSUE TITLE
Deployment: current status

### ISSUE THREAD

**Issue by LndH** [osoc22/technical-support#13]
**Is your project already deployed somewhere ? If so, where ? If not, what do you need ?**
 Yes, a version of our project is already deployed at https://osoc22.github.io/project-vanhout/app/
 We're going to showcase our project on https://osoc22.github.io/project-vanhout/docs/ using the template: https://osoc18.github.io/website/
 
 **I'll create a sub-domain name ```*```.osoc.be for your project! Do you only have a front-end or is there also a back-end ?**
 We only have a front-end (ReactJS app)

**Comment by jbelien** [comment]
Thanks for the update @LndH !

So do you confirm that you don't need anything regarding deployment or domain name ?

**Comment by LndH** [comment]
@jbelien We do not need any further assistance with deployment or domain name. Sorry for the delayed reply, I was waiting for my team mates to give their opinion regarding the domain name.

**Comment by jbelien** [comment]
No worries! 😃
