### ISSUE TITLE
connect netlify to osoc domain

### ISSUE THREAD

**Issue by rtalwar2** [osoc22/technical-support#14]
It's deployed on Netlify: https://master--roaring-wisp-a28b9a.netlify.app/

Can you link it to https://the-impact-of-sharing-knowledge.osoc.be/ :)

thanks!

**Comment by jbelien** [comment]
I don't have the information I need!

This is what I need:
![image](https://user-images.githubusercontent.com/1150563/180747619-330863e4-df78-467b-9e1c-1f9bb432cba8.png)

**Comment by rtalwar2** [comment]
Where can I get that information exactly? can't you point to https://master--roaring-wisp-a28b9a.netlify.app

**Comment by jbelien** [comment]
It's in the documentation: https://help.osoc.be/global/tools/deployment#sub-domain-.osoc.be

**Comment by rtalwar2** [comment]
sorry, I don't understand. Do I have to do something here?
![image](https://user-images.githubusercontent.com/105129606/180775805-df7d516f-950f-4de7-b820-bb5069bd61a9.png)

**Comment by rtalwar2** [comment]
or maybe if it's easier I can go into a call on discord.

**Comment by jbelien** [comment]
> sorry, I don't understand. Do I have to do something here?

Yes, click on "Add custom domain" and follow the steps.
You "custom domain" will be `the-impact-of-sharing-knowledge.osoc.be`

**Comment by rtalwar2** [comment]
![image](https://user-images.githubusercontent.com/105129606/180793746-2c07f5fc-4d2a-4be2-9d48-929cf5ac8183.png)
I can't use that domain.

**Comment by jbelien** [comment]
Ah fuck ... Sorry, I indeed forgot about that!

![image](https://user-images.githubusercontent.com/1150563/180799929-560f22ce-d071-4a15-b658-016a06d66448.png)

Go to "Edit site name" and put `the-impact-of-sharing-knowledge` so your front-end will be `the-impact-of-sharing-knowledge.netlify.app`

**Comment by rtalwar2** [comment]
ah, only that. Thanks, it works now.
