### ISSUE TITLE
Activate GitHub Pages for Pleasant Procedures

### ISSUE THREAD

**Issue by Speedbuilder** [osoc22/technical-support#15]
We would like to activate the GitHub Pages feature for our project. The branch on which we will put everything is the following: https://github.com/osoc22/project-digital-wallet/tree/gh-pages

**Comment by LotuxPunk** [comment]
Should be good : https://osoc22.github.io/project-digital-wallet/ tell me if it's not the case 👀

**Comment by Speedbuilder** [comment]
Thank you for the lightning-fast service!
