### ISSUE TITLE
Github pages for Inspector widget

### ISSUE THREAD

**Issue by tischany** [osoc22/technical-support#17]
Hi Clément,
Could you enable github pages for our repo please?

**Comment by LotuxPunk** [comment]
Hi ! On which branch ?

**Comment by tischany** [comment]
I made a new branch gh-pages

**Comment by LotuxPunk** [comment]
Should be good ! https://osoc22.github.io/project-inspector-widget/

**Comment by tischany** [comment]
Thank you!
