### ISSUE TITLE
Get a custom domain

### ISSUE THREAD

**Issue by Victor-Vansteenkiste** [osoc22/technical-support#18]
**Is your request related to a problem? Please describe.**

Currently our web interface is running on a random generated domain, is it possible to get a custom domain (something that looks a bit more professional)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LotuxPunk** [comment]
Where should redirect the domain ? 👀

Do you have any TXT or CNAME directive from your deployment service ?

**Comment by Victor-Vansteenkiste** [comment]
https://golden-fairy-c58151.netlify.app/#/

it should link to this :))

**Comment by jbelien** [comment]
![image](https://user-images.githubusercontent.com/1150563/181022333-03799952-427e-40a9-bbf8-723faef82227.png)

Follow these steps and put `inspector-widget.netlify.app` (instead of `golden-fairy-c58151.netlify.app`)!

**Comment by Victor-Vansteenkiste** [comment]
Perfect, thanks!
