### ISSUE TITLE
Apply new teams name

### ISSUE THREAD

**Issue by jbelien** [osoc22/technical-support#2]
- [x] GitHub Teams
- [ ] ~GitHub Repositories~
- [x] Create labels for Technical Support issues

@LotuxPunk: Nothing to worry about, I'll take care of it this weekend.
@mietcls: Where can I find all the team names and crests ? Thanks!

**Comment by jbelien** [comment]
I'll also create the 2022 page on https://osoc.be/

**Comment by mietcls** [comment]
Thanks Jonathan! You'll find the names on the [project sheet](https://docs.google.com/spreadsheets/d/1kYlOkmtwzf7le9x_HVQ8tdbAn6gg2xG2tNKE-qMEm-Q/edit?usp=sharing), but they're not all updated yet. I'll ping you when it's done.
