### ISSUE TITLE
Change the GH Pages branch to "gh-pages" on the IDLab project

### ISSUE THREAD

**Issue by DemianD** [osoc22/technical-support#5]
**Is your request related to a problem? Please describe.**

**Describe the solution you'd like**

Point the GitHub Pages location to the "gh-pages" branch of the IDLab Project: https://github.com/osoc22/project-idlab/tree/gh-pages

Or if possible, give @th0rgall and @DemianD admin rights on that repo. 

**Describe alternatives you've considered**

/

**Additional context**

/

**Comment by LotuxPunk** [comment]
Should be good, also I added you and @th0rgall as admin on this repo ✅

**Comment by DemianD** [comment]
Thank you @LotuxPunk!
