### ISSUE TITLE
deploying on GitHub pages, no access to repo settings

### ISSUE THREAD

**Issue by LndH** [osoc22/technical-support#6]
**Is your request related to a problem? Please describe.**
We want to deploy the current version of our project on GitHub pages, but we do not have access to the corresponding settings in our repository.

**Describe the solution you'd like**
If possible, access to those settings.

**Describe alternatives you've considered**
Having someone else enable them for us, but it would be most convenient for us to get access to those settings ourselves, so we can do the deployment on our own as a team.

**Additional context**
Here, you can see a screenshot of the settings I had access to for the project I was on last year.
![Screenshot 2022-07-13 at 15 38 04](https://user-images.githubusercontent.com/17167523/178747179-9d787dc1-2517-49ea-b91f-9af4855fc45e.png)

**Comment by LotuxPunk** [comment]
Hey ! As said on Discord, you might want to consider using Netlify or Vercel or Heroku to deploy it. It's as easy as using GH-Pages, don't worry!

As explained on the wiki:
> Even though, it's possible to use GitHub Pages to deploy your project, we recommend not to use it because it will be used to deploy the page to present your project (during Week 4).



You can find the documentation on the help.osoc.be website: https://help.osoc.be/global/tools/deployment 

If you're having an hard time to use Netlify or Vercel, I can give you a hand to get started with it !

**Comment by LndH** [comment]
@LotuxPunk why can't we just do it like the IDLab project?

https://osoc22.github.io/project-idlab/app/
https://osoc22.github.io/project-idlab/docs/

**Comment by Denperidge** [comment]
Hi, IDLab's very own discourse Cat here!

While I do agree that Netlify/Vercel can be incredibly easy to use, two things should be noted, which influenced our decision to opt for gh-pages.
- External dependency: in terms of longevity, every new platform that a project depends on is a possible point of failure for the future
- Overkill: Heroku's (and if I'm correct, Netlify and Vercel as well) big advantage is supporting dynamic websites and back-ends. These services are overequipped - and thus underperform (even if its with ms's difference) - as opposed to clear-cut static hosts. [Many server frameworks even discourage serving static files from the same code that runs your back-end](https://expressjs.com/en/starter/static-files.html)
  > NOTE: For best results, [use a reverse proxy](https://expressjs.com/en/advanced/best-practice-performance.html#use-a-reverse-proxy) cache to improve performance of serving static assets.

Do note that I'm posting this NOT to disagree with Netlify/Vercel hosting or OSOC's recommendation for them: mixing your static host on gh-pages together with your documentation can get _messy_, and a lot of teams will either have an easier time with - or simply require - an external host. But I wanted to throw in my two cents!

**Comment by LotuxPunk** [comment]
> @LotuxPunk why can't we just do it like the IDLab project?
> 
> https://osoc22.github.io/project-idlab/app/ https://osoc22.github.io/project-idlab/docs/

If you take a look to @osoc22/project-idlab `gh-pages` branch, you can see that they've done something different on this particular branch.

**Comment by jbelien** [comment]
> If you take a look to @osoc22/project-idlab `gh-pages` branch, you can see that they've done something different on this particular branch.

That was indeed what I was going to reply...

@osoc22/project-idlab started a new (orphan) branch to be deployed on GitHub Pages.
I'm hoping they will split the static website and the docs in a clean way in that branch but that's what they told me so no worries there.

This is NOT what's happening in https://github.com/osoc22/project-vanhout/tree/gh-pages where I see that `gh-pages` branch is currently "synced" with `master` branch.

**Comment by LndH** [comment]
We're going to do the deployment tomorrow and take a look at it then. I know it's not done properly at the moment ;)

**Comment by LotuxPunk** [comment]
> Hi, IDLab's very own discourse Cat here!
> 
> While I do agree that Netlify/Vercel can be incredibly easy to use, two things should be noted, which influenced our decision to opt for gh-pages.
> 
>     * External dependency: in terms of longevity, every new platform that a project depends on is a possible point of failure for the future
> 
>     * Overkill: Heroku's (and if I'm correct, Netlify and Vercel as well) big advantage is supporting dynamic websites and back-ends. These services are overequipped - and thus underperform (even if its with ms's difference) - as opposed to clear-cut static hosts. [Many server frameworks even discourage serving static files from the same code that runs your back-end](https://expressjs.com/en/starter/static-files.html)
>       > NOTE: For best results, [use a reverse proxy](https://expressjs.com/en/advanced/best-practice-performance.html#use-a-reverse-proxy) cache to improve performance of serving static assets.
> 
> 
> Do note that I'm posting this NOT to disagree with Netlify/Vercel hosting or OSOC's recommendation for them: mixing your static host on gh-pages together with your documentation can get _messy_, and a lot of teams will either have an easier time with - or simply require - an external host. But I wanted to throw in my two cents!

I don't think this ticket is the right place to debate this, but I honestly think your arguments holds water. ✅
