### ISSUE TITLE
OSOC cname for digital wallet project

### ISSUE THREAD

**Issue by Speedbuilder** [osoc22/technical-support#7]
Could the [Pleasant Procedures](https://github.com/osoc22/project-digital-wallet) team get a CNAME record for our project?
pleasant-procedures.osoc.be is the requested subdomain/CNAME and it should point to [http://pleasant-procedures.vercel.app/](http://pleasant-procedures.vercel.app/)

**Comment by jbelien** [comment]
Hello @Speedbuilder ,

I've added `pleasant-procedures.osoc.be` to our DNS.

![image](https://user-images.githubusercontent.com/1150563/179717613-c484d948-03b7-45c6-b426-3aa59cb79648.png)

You should now be able to add it to your Vercel "project".

Let us know when it's done (and if something is not working).

**Comment by jbelien** [comment]
@osoc22/pleasant-procedures Any update ?

**Comment by Speedbuilder** [comment]
@jbelien I was literally writing this as you reacted :D

We have the following issue when we go to [pleasant-procedures.osoc.be](http://pleasant-procedures.osoc.be):

![image](https://user-images.githubusercontent.com/41786850/180722663-cd2501ba-9c66-4171-b172-b45022aa89f2.png)

I think that OSOC on Vercel should add the TXT record, is that something you can do?

**Comment by jbelien** [comment]
> I think that OSOC on Vercel should add the TXT record, is that something you can do?

Indeed, no worries!
Copy paste the value, I'll add it to our DNS.

**Comment by Speedbuilder** [comment]
`vc-domain-verify=pleasent-procedures.osoc.be,a075d1653c830a9b1b2a`

Thank you!

**Comment by jbelien** [comment]
@Speedbuilder Should be good! Let me know if it's working (or not).

**Comment by Speedbuilder** [comment]
@jbelien Not working so far:

![image](https://user-images.githubusercontent.com/41786850/180738819-36e956d6-7913-4308-bfe5-f303148d79b3.png)

It's giving a different value for the TXT record now: `vc-domain-verify=pleasant-procedures.osoc.be,bb2ed95aab71d6163a58`

**Comment by LotuxPunk** [comment]
TXT uuid seems to have changed in the process.

`vc-domain-verify=pleasent-procedures.osoc.be,a075d1653c830a9b1b2a` -> `vc-domain-verify=pleasent-procedures.osoc.be,bb2ed...`

**Comment by jbelien** [comment]
Updated!

**Comment by jbelien** [comment]
@osoc22/pleasant-procedures Try avoid pushing anything until it's validated!

**Comment by Speedbuilder** [comment]
Pushing anything to master/main or also other branches?

Edit: took a couple of minutes for the DNS records to renew probably but the deployment is working now.

Thank you @jbelien!
