### ISSUE TITLE
Personal access token for GitHub container registry on osoc22 organization

### ISSUE THREAD

**Issue by juliavdkris** [osoc22/technical-support#8]
**Is your request related to a problem? Please describe.**
Hi! We're setting up our pipeline, and need somewhere to push the built Docker images.

**Describe the solution you'd like**
I like using GitHub's container registry for this, but that would mean we need a personal access token for the osoc22 organization. The [default GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) doesn't seem to have the `write:packages` permission unfortunately, so one would have to be manually created. You can contact me on Discord (`WarKitteh#2473`) or matrix (`@juliavdkris:matrix.org`), since posting the token here is *probably* a bad idea :p  
Or just add it as a secret to [our repo](https://github.com/osoc22/project-abb), I don't think we actually need to have the token ourselves (though it might be nice just in case, for quick fixes?)

**Describe alternatives you've considered**
I could also push the image to my personal account. But sustainability-wise, I think it would be better to have it on the official osoc22 organization.

**Additional context**
N/A

**Comment by jbelien** [comment]
Hello @juliavdkris,

AFAIK there is no "organization token".
You will have to create a [Personal Access Token (PAT)](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and use it as a secret.

I've enabled public packages for osoc22 organization ; you should be allow to publish your package.
Check the [documentation](https://docs.github.com/en/packages/working-with-a-github-packages-registry) to see how to upload your package (depending type of package).

Ping me if you have any issue to publish your package.

**Comment by juliavdkris** [comment]
Ahhh I didn't know members of an organization could use their own PAT to push to GHCR. Awesome, thank you!
